name: Publish wiki
on:
  push:
    branches: [wiki_workflow]
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
